"""Aumentar tamaño de columnas encriptadas

Revision ID: cee05e1415bd
Revises: 1d15657b71c3
Create Date: 2025-05-15 08:47:39.807239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cee05e1415bd'
down_revision: Union[str, None] = '1d15657b71c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicamentos', 'precio', 
        existing_type=mysql.FLOAT(),
        type_=sa.Integer(),
        nullable=False)
    op.alter_column('medicamentos', 'cantidad_disponible',
        existing_type=mysql.INTEGER(),
        nullable=False)
    op.alter_column('medicos', 'documento',
        existing_type=mysql.VARCHAR(length=25),
        nullable=False)
    op.create_unique_constraint(None, 'medicos', ['documento'])
    op.alter_column('pacientes', 'documento',
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=25),
        existing_nullable=False)
    op.alter_column('pacientes', 'telefono',
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.String(length=512),
        existing_nullable=True)
    op.alter_column('pacientes', 'email',
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=512),
        existing_nullable=True)
    op.alter_column('medicos', 'telefono',
        existing_type=sa.String(length=20),
        type_=mysql.VARCHAR(length=512),
        existing_nullable=False)
    op.alter_column('medicos', 'email',
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=512),
        existing_nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pacientes', 'email',
        existing_type=sa.String(length=512),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True)
    op.alter_column('pacientes', 'telefono',
        existing_type=sa.String(length=512),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=True)
    op.alter_column('pacientes', 'documento',
        existing_type=sa.String(length=25),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False)
    op.drop_constraint(None, 'medicos', type_='unique')
    op.alter_column('medicos', 'documento',
        existing_type=mysql.VARCHAR(length=25),
        nullable=True)
    op.alter_column('medicamentos', 'cantidad_disponible',
        existing_type=mysql.INTEGER(),
        nullable=True)
    op.alter_column('medicamentos', 'precio',
        existing_type=sa.Integer(),
        type_=mysql.FLOAT(),
        nullable=True)
    op.alter_column('medicos', 'email',
        existing_type=mysql.VARCHAR(length=512),
        type_=sa.String(length=100),
        existing_nullable=False)
    op.alter_column('medicos', 'telefono',
        existing_type=mysql.VARCHAR(length=512),
        type_=sa.String(length=20),
        existing_nullable=False)
    # ### end Alembic commands ###
