from .cita import Cita
from .consultorio import Consultorio
from .diagnostico import Diagnostico
from .especialidad import Especialidad
from .examen import Examen
from .factura import Factura
from .historial_medico import HistorialMedico
from .horario_medico import HorarioMedico
from .medicamento_recetado import MedicamentoRecetado
from .medicamento import Medicamento
from .medico import Medico
from .paciente import Paciente
from .pago import Pago
from .receta import Receta
from .resultado_examen import ResultadoExamen
from .rol import Rol
from .usuario import Usuario